//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace var2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListTimeTableForWorker
    {
        public int id { get; set; }
        public int idWorker { get; set; }
        public int idTimeTable { get; set; }
    
        public virtual TimeTable TimeTable { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
