//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace var2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class var2Entities : DbContext
    {
        public var2Entities()
            : base("name=var2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appel> Appel { get; set; }
        public virtual DbSet<ListAnalysisAndProcedure> ListAnalysisAndProcedure { get; set; }
        public virtual DbSet<ListPositions> ListPositions { get; set; }
        public virtual DbSet<ListTimeTableForWorker> ListTimeTableForWorker { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<Reception> Reception { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TimeTable> TimeTable { get; set; }
        public virtual DbSet<Treatment> Treatment { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
