//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace var2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int idTreatment { get; set; }
        public System.DateTime dateStart { get; set; }
        public int idReception { get; set; }
        public int idAnalysis { get; set; }
    
        public virtual ListAnalysisAndProcedure ListAnalysisAndProcedure { get; set; }
        public virtual Reception Reception { get; set; }
    }
}
