//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace var2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.ListTimeTableForWorker = new HashSet<ListTimeTableForWorker>();
        }
    
        public int idWorker { get; set; }
        public string fio { get; set; }
        public int idPosition { get; set; }
        public string password { get; set; }
        public int idAppel { get; set; }
        public int idReception { get; set; }
        public int idTimeTable { get; set; }

        public string TakePosition { get => ListPositions.title; }
        public string TakeReception { get => Reception.noteOfInspection; }
        public string TakeReceptionDate { get =>Convert.ToString(Reception.date); }


        public string TakeApel { get => Appel.complaint; }
        public string TakeFioClientFromAppel { get => Appel.TakeFioClient; }


        public virtual Appel Appel { get; set; }
        public virtual ListPositions ListPositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListTimeTableForWorker> ListTimeTableForWorker { get; set; }
        public virtual Reception Reception { get; set; }
    }
}
